### ISSUE TITLE
How to update IMAGE_BASE_URL data

### ISSUE THREAD

**Issue by NappyBoyTheory** [manuelpires/nft-collection-generator#2]
Is there a way to update the metadata for the image_base_url after create a collection? I have my nfts and metadata but i want to update the url so it can show my .png in the browser after uploading files to Pinata. Other than this everything is awesome! Ive been trying to find the right code that works for me for about a week or so

**Comment by manuelpires** [comment]
Hello! There's no way to update the `image` property in the metadata files after running the project. As you can see in the code, the process just uses the `IMAGE_BASE_URL` and the `tokenId` to build that `image` property for each one of the metadata files at runtime. The process assumes that you already know what the base URL will be. Nevertheless you could easily create and run a simple script that loads each metadata file, updates the property, and saves it again 😃

**Comment by NappyBoyTheory** [comment]
Thats exactly what im trying to do lol. Looks like i got more learning to do. Once again thanks for this whole script. Its taken so much weight off my shoulders

**Comment by manuelpires** [comment]
Awesome good luck with that! I'm glad you found the script useful 🙂

**Comment by manuelpires** [comment]
This can now be done in [v1.0.1](https://github.com/manuelpires/nft-collection-generator/releases/tag/v1.0.1) 🙂
